### PR TITLE
16 add bio info page

### PR DESCRIPTION
**Pull request by h602121**
Added welcome/stepFour and created bio info page. Also created components/notificationPopup with dynamic inputs to be used different places e.g when pressing submit button. Changed styles to match figma design

### CODE REVIEW

**Review by Ic4rus90 — DISMISSED** [review]
[eslint] 
src\components\form\textInput\index.js
  Line 8:1:  Delete `⏎`  prettier/prettier

Search for the keywords to learn more about each error.

**Comment by h602121** [comment]
I dont have that error? Line 8 isnt a space, so that error shouldnt exist

**Comment by h602121** [comment]
Main is pulled

**Review by Brandsegg — APPROVED** [review]
Good!

**Review by Ic4rus90 — APPROVED** [review]
Gucci

**Pull request merged**
